export const PROGRAMMING_REQUEST = 'PROGRAMMING_REQUEST';
export const PROGRAMMING_FAILURE = 'PROGRAMMING_FAILURE';
export const PROGRAMMING_SUCCESS = 'PROGRAMMING_SUCCESS';
export const PROGRAMMING_SINGLE_REQUEST = 'PROGRAMMING_SINGLE_REQUEST';
export const PROGRAMMING_SINGLE_FAILURE = 'PROGRAMMING_SINGLE_FAILURE';
export const PROGRAMMING_SINGLE_SUCCESS = 'PROGRAMMING_SINGLE_SUCCESS';