export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const REQUEST_OPEN_MODAL = 'REQUEST_OPEN_MODAL';
export const REQUEST_CLOSE_MODAL = 'REQUEST_CLOSE_MODAL';

export const SEND_USER_INFO = 'SEND_USER_INFO';
export const USER_INFO_UPDATED = 'USER_INFO_UPDATED';
export const USER_INFO_FAILED = 'USER_INFO_FAILED';