export const GAMING_REQUEST = 'GAMING_REQUEST';
export const GAMING_FAILURE = 'GAMING_FAILURE';
export const GAMING_SUCCESS = 'GAMING_SUCCESS';
export const GAMING_SINGLE_REQUEST = 'GAMING_SINGLE_REQUEST';
export const GAMING_SINGLE_FAILURE = 'GAMING_SINGLE_FAILURE';
export const GAMING_SINGLE_SUCCESS = 'GAMING_SINGLE_SUCCESS';