export const CONTENT_REQUEST = 'CONTENT_REQUEST';
export const CONTENT_FAILURE = 'CONTENT_FAILURE';
export const CONTENT_SUCCESS = 'CONTENT_SUCCESS';
export const CONTENT_SINGLE_REQUEST = 'CONTENT_SINGLE_REQUEST';
export const CONTENT_SINGLE_FAILURE = 'CONTENT_SINGLE_FAILURE';
export const CONTENT_SINGLE_SUCCESS = 'CONTENT_SINGLE_SUCCESS';